const {chromium}=require('C:/Users/noc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:4173/',{waitUntil:'networkidle'});await page.locator('.menu-item').first().waitFor();await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'review/desktop-1440.png',fullPage:false});
 const layouts=[];
 for(const width of [375,390,430,768,1440,1920]){
  await page.setViewportSize({width,height:width<500?844:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(150);
  const result=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,heading:document.querySelector('h1').getBoundingClientRect().toJSON(),images:[...document.images].filter(i=>!i.closest('dialog')).map(i=>({src:i.getAttribute('src'),loaded:i.complete&&i.naturalWidth>0})),overflow:[...document.querySelectorAll('body *')].filter(e=>!e.closest('dialog')&&!e.closest('.category-nav')&&getComputedStyle(e).position!=='fixed'&&e.getBoundingClientRect().width>0&&e.getBoundingClientRect().right>innerWidth+1).slice(0,15).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right}))}));if(result.scrollWidth>width)throw new Error('Horizontal body overflow at '+width);if(result.overflow.length)throw new Error('Unclipped overflow at '+width);layouts.push(result);
  if(width===390)await page.screenshot({path:'review/mobile-390.png'});
  await page.locator('#speisekarte').scrollIntoViewIfNeeded();await page.waitForTimeout(100);if([390,768,1440].includes(width))await page.screenshot({path:`review/menu-${width}.png`});
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));
 await page.locator('#menu-toggle').click();if(await page.locator('#mobile-nav').getAttribute('open')===null)throw new Error('mobile nav missing');await page.locator('#mobile-nav a[href="#speisekarte"]').first().click();if(await page.locator('#mobile-nav').getAttribute('open')!==null)throw new Error('mobile nav close failed');
 await page.locator('#menu-search').fill('Carbonara');if(await page.locator('.menu-item').count()!==2)throw new Error('global search expected two Carbonara dishes');await page.locator('#menu-search').fill('inside out');if(await page.locator('.menu-item').count()<9)throw new Error('category search failed');await page.locator('#menu-search').fill('xzznonexistent');if(!await page.locator('.empty-results').isVisible())throw new Error('empty result state failed');await page.locator('[data-reset-search]').click();
 await page.locator('#category-nav [data-category="pizze"]').click();await page.locator('[data-add="pizze-701"]').click();await page.locator('[data-add="pizze-701"]').click();
 await page.locator('[data-group="food"]').click();await page.locator('#category-nav [data-category="insalate"]').click();await page.locator('[data-add="insalate-505"]').click();await page.locator('[data-variant="1"]').click();
 await page.locator('.header-cart').click();const expected='25,30';if(!(await page.locator('#cart-summary .total-line').innerText()).includes(expected))throw new Error('cart arithmetic should be 2*9.90+5.50');await page.screenshot({path:'review/cart-mobile.png'});await page.keyboard.press('Escape');
 await page.reload({waitUntil:'networkidle'});await page.locator('.header-cart').click();if(!(await page.locator('#cart-summary .total-line').innerText()).includes(expected))throw new Error('persist cart failed');
 const decrease=page.locator('[data-cart-change="pizze-701:0"][data-delta="-1"]');await decrease.click();if(!(await page.locator('#cart-summary .total-line').innerText()).includes('15,40'))throw new Error('decrease total wrong');await page.locator('[data-remove="insalate-505:1"]').click();if(!(await page.locator('#cart-summary .total-line').innerText()).includes('9,90'))throw new Error('remove wrong');await page.locator('#clear-cart').click();if(!await page.locator('.cart-empty').isVisible())throw new Error('clear cart failed');await page.keyboard.press('Escape');
 await page.locator('[data-group="drinks"]').click();await page.locator('#category-nav [data-category="bevande-calde"]').click();if(await page.locator('.menu-item').count()!==11)throw new Error('hot drinks incomplete');if(await page.locator('#menu-items [data-add]').count()!==0)throw new Error('unknown prices added to cart');
 await page.locator('#original-menu').click();await page.locator('#lightbox-image').evaluate(i=>new Promise(r=>{if(i.complete)r();else i.onload=r;}));if(!await page.locator('#lightbox-image').evaluate(i=>i.naturalWidth>0))throw new Error('original menu missing');await page.keyboard.press('Escape');
 await page.locator('[data-group="sushi"]').click();await page.locator('[data-filter="scharf"]').click();if(await page.locator('.menu-item').count()!==6)throw new Error('explicit spicy tags incorrect');
 const data=await page.evaluate(async()=>await(await fetch('data/menu.json')).json());const all=data.categories.flatMap(c=>c.items);const count=all.length;const unique=new Set(all.map(i=>i.id)).size;if(unique!==count)throw new Error('duplicate IDs');
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload({waitUntil:'networkidle'});const titleCount=await page.locator('h1').count();if(titleCount!==1)throw new Error('H1 count');
 await page.evaluate(()=>localStorage.setItem('la-mela-doro-cart-v1','[{"id":"pizze-701","variant":0,"quantity":-99},{"id":"fake","variant":0,"quantity":2}]'));await page.reload({waitUntil:'networkidle'});if(await page.locator('.header-cart [data-cart-count]').textContent()!=='0')throw new Error('bad stored data not filtered');await page.evaluate(()=>localStorage.removeItem('la-mela-doro-cart-v1'));
 if(errors.length)throw new Error('browser errors: '+errors.join(';'));
 fs.writeFileSync('review/qa-results.json',JSON.stringify({layouts,count,categories:data.categories.length,needsReview:all.filter(i=>i.needsReview).length,functional:'passed',errors},null,2));console.log(JSON.stringify({layouts:layouts.map(l=>({width:l.width,scrollWidth:l.scrollWidth,overflow:l.overflow})),count,categories:data.categories.length,functional:'passed',errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
